# Generated by Django 4.1.7 on 2023-05-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_clientes'),
        ),
    ]
