# Generated by Django 4.1.7 on 2023-05-26 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publi',
            options={'verbose_name': 'publicação', 'verbose_name_plural': 'Publicações'},
        ),
    ]
