# Generated by Django 4.1.7 on 2023-05-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0002_alter_publi_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publi',
            old_name='user',
            new_name='author',
        ),
    ]
