# Generated by Django 4.1.7 on 2023-05-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0004_rename_author_publi_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publi',
            old_name='user',
            new_name='author',
        ),
    ]
