# Generated by Django 4.1.7 on 2023-05-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0005_rename_user_publi_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='publi',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_feed'),
        ),
    ]
